{% set name = "fprettify" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pseewald/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 052da19a9080a6641d3202e10572cf3d978e6bcc0e7db29c1eb8ba724e89adc7
  patches:
    - find_package.patch

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - {{ name }} = {{ name }}:run

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - configargparse

test:
  requires:
    - python {{ python_min }}
  source_files:
    - fortran_tests/
    - run_tests.py
  imports:
    - {{ name }}
  commands:
    - {{ name }} --version
    - python run_tests.py

about:
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Auto-formatter for modern fortran source code
  home: https://github.com/pseewald/fprettify/

extra:
  recipe-maintainers:
    - awvwgk
